### ISSUE TITLE
Issues with large set of vectors X

### ISSUE THREAD

**Issue by jwkirchenbauer** [mkarppa/deann#1]
Hi! Thanks for writing a fast library to accompany your paper.

I'm interested in testing out using this approach at scale. I installed the library and walked through the tutorial steps with the shuttle data. Then I substituted in some of my own data with shape 4M x 768 for `X` (comes from a neural model) and at first my python kernel just died. Then I realized that this step at the very end of the tutorial would give me an actual error:
```
annp = deann.AnnEstimatorPermuted(h, 'exponential', k, m, fivf)
annp.fit(X)

>> ValueError: cannot create std::vector larger than max_size()
```

I was trying to figure out what could be happening and I computed that the max value of int32 would be 2,147,483,647, and if my vectors were 768 dim, then the max number of vectors in my X matrix I'd be able to have before the total number of entries was > max int32 would be 2,147,483,647 / 768 = 2796202.66.

I checked the operation above at values lower than 2796202 and it worked, and for 2796203 and higher it gave that error. It's a bit funny if that happened and is just a coincidence... but I can't really figure out what part of your code is the actual vector allocation that is failing because the error output doesn't give me a line number or anything obviously.

I thought it might be the permutation part, but the NaiveKde also seems to have the same issue with large X, but the crashes don't line up with that back of envelope math above.

feel free to email me jkirchen@umd.edu if that's better for you!

**Comment by mkarppa** [comment]
Hi John!

By eyeballing my code, my first guess would be that it is caused by line 435 in AnnEstimator.hpp.
      Xpermuted = std::vector<T>(this->n * this->d);
Variables n and d are declared on lines 214 and 215 of KdeEstimator.hpp as ints which on most systems would indeed be int32s. 
As such this would cause a signed integer overflow at n >=  2796203.
NaiveKDE works differently because it never constructs this Xpermuted matrix, and as such, this particular allocation never takes place, so an error there would have to take place somewhere else, but I think it might also be related to signed integer overflow.

I don't have the time to work on this right now, but I'll try to get this fixed soonish (maybe next week). As a first remedy, you could try to change the variables n and d into int64s and see if that fixes it.

**Comment by jwkirchenbauer** [comment]
1) unbelievable response time on a 2yr old project, thank you
2) awesome, thanks for giving me a little bit of signal that what I arrived at was actually a reasonable explanation

My c++ is rusty (i.e. undergrad memories only) so I will do my best to poke it and rebuild along the int64 avenue.

Silly, basic question, is there a way for me to set things up so that I get a bit more informative backtrace? I noticed a commented line in the top cmake for some "accessors" but I don't really know what that did when I uncommented it.
More generally, how would you approach debugging the underlying library with a slightly less black box `edit->build->rerun python code` cycle I am about to try?

**Comment by mkarppa** [comment]
The library is a bit tricky to debug on the fly because the codeflow has so many levels of indirection (you call the library from Python, so it goes through CPython, then it enters C++ domain, and then comes back again). It might be easier to setup a debugger if you directly try to access the C++ interface. On the other hand, if the code is compiled with debug symbols, it might be possible to start CPython through GDB and then try to poke it.

However, I realized when looking at the code that simply changing the types at that point won't do you much good because the entire arrays library uses ints for passing array lengths. That will have to be updated to make use of 64-bit integers.

There never was a good reason why I used ints in the first place, but I guess it didn't occur to me that the arrays could be so huge at that point. And it only becomes an issue with the kind of data sizes you're handling. This will take a moment, but I'll try to have it fixed soon.

**Comment by jwkirchenbauer** [comment]
Okay cool! I was thinking debug symbols, but since you believe that there is a bit of a more in-depth refactor needed to change to supporting int64 indexes and stuff, I think I'll wait a bit to let you take a crack at it if you have time.

Overall, my interest in your method is precisely because even in the simple naive, exact case, my experience with your tutorial examples plus my data suggests that your c++ and MKL based implementation of a basic KDE for euclidean kernels is _significantly_ faster than the scikit-learn implementation (though I haven't verified whether scikit is handicapped due to improper install of [numpy/scipy/scikit](https://scikit-learn.org/stable/computing/parallelism.html) whiles trying to build `deann`). 

I have access to a many core cpu server and so, after removing the single thread commands you suggest for timing consistenty, it really flies in comparison to scikit right now. Did you observe such improvement over scikit in apples to apples settings?

Then of course, I intend to scale beyond the naive regime, where the faiss backend and efficient sample routine become critical, and of course, your work building an interface for the algorithm minimizes my startup effort considerably (and it would take me ages to write my own CPython version)

**Comment by mkarppa** [comment]
Ok, it's coming back to me now, the interface was designed to be compatible with MKL as it works by default which is with 32-bit integers for passing array lengths. In order to migrate to 64-bit integers, I need to make some routine changes to the code. I'll try to get that done.

The nice thing about MKL is that since what my library is doing is essentially just doing a bunch of (low-level) array calls, so if you allow multithreading to take place, you get all the speed benefits of multithreading etc. essentially for free as long as you keep to working on sufficiently large chunks of data at once.

I didn't explore the comparisons against sklearn very much in practice (as in what one might do with a lot of data and multithreading to the fullest), apart from what's reported in the paper, as this project had a specific focus, but my understanding is that sklearn often prioritizes versatility over raw computing power.

Anyway, I've been able to locate the issue and am working on fixing it, it just takes some time because I need to update the interface to the array functions (and update the integer types everywhere those are used).

**Comment by jwkirchenbauer** [comment]
I really appreciate it! Both the original work and your willingness to try and help extend its scaling ability a little bit for me now.

I will await news/relevant pushes and after that will keep you updated about my progress with the toolkit (especially if I get some nice results re: performance).

**Comment by mkarppa** [comment]
This turns out to be an even more extensive overhaul than I hoped for. I need to essentially edit every aspect of the library. Right now I found out that I even have to change the random number generator (because it works with 32 bit numbers). Also the way MKL has been linked has been changed (from the default LP64 interface to ILP64 interface). So we'll get there eventually.

**Comment by mkarppa** [comment]
The changes have been made. I believe it should work now. However, be advised that some NN libraries might fail with such large inputs (like FAISS, I'm getting a floating point exception with datasets >= 2^32 vectors, but I didn't try to figure out what's wrong).

Please open up another issue if the problem persists or if you have some other problems with the library.
